### ISSUE TITLE
Fireshard item does not produce lava on right-click

### ISSUE THREAD

**Issue by Not-February** [DoctorWiggles/GrimoireOfGaia#6]
Exactly what it says on the tin. Using GoG 1.4.3, haven't had the opportunity to update to the latest yet but it doesn't seem like this was relevant to that anyways.

On another note, I also notice there is no JEI brewing recipe for mature nether wart, though I'm pretty sure it was usable in previous versions to make awkward potions.

**Comment by DoctorWiggles** [comment]
You would be correct :^)
[Fixed them both in](https://github.com/DoctorWiggles/GrimoireOfGaia/releases/tag/1.4.0-ALPHA) b3ada36 for 1.4.5

**Comment by Not-February** [comment]
Cool, I'll update to that and see whether they are functional. You're quite fast! Haha.

**Comment by Not-February** [comment]
Looks like the fireshard is working now and correctly spawns lava, but the second thing - the mature nether wart - still seems to not have a brewing recipe, at least as far as JEI is concerned. Will have to test it manually to be sure.

**Comment by DoctorWiggles** [comment]
Yeah that's odd, I might have to go poke the devs and see what's going on their end of things.
