### ISSUE TITLE
Crashing on rendering screaming ender girl dragon

### ISSUE THREAD

**Issue by misterfixit** [DoctorWiggles/GrimoireOfGaia#9]
https://gist.github.com/anonymous/da85a8305390b54ae2b94b8e8826ecf0

**Comment by DoctorWiggles** [comment]
Odd, when does this happen? Is it random or are you able to consistently reproduce it?

**Comment by misterfixit** [comment]
As far as I'm aware it's only happened to one user.

**Comment by DoctorWiggles** [comment]
Alright, think I've found the problem, should be fixed in the [new version 1.4.8](https://github.com/DoctorWiggles/GrimoireOfGaia/releases/tag/1.4.0-ALPHA)  ed9e00c

Lemme know if that works out all fine.

**Comment by misterfixit** [comment]
I'll test after work and get back to you

**Comment by DoctorWiggles** [comment]
Assuming this has been resolved

**Comment by misterfixit** [comment]
Yup no issue since, apologies I meant to close this.

**Comment by DoctorWiggles** [comment]
All good :^)
